import type { CampStats, NightEventCard, NightEventTag, PlayerStats } from "../game/types";

type CardSpec = {
  id: string;
  sceneType: "PATROL" | "CAMP";
  title: string;
  outcome: string;
  tags: NightEventTag[];
  player?: Partial<PlayerStats>;
  camp?: Partial<CampStats>;
  routeTemplates?: string[];
  observationPool: string[];
};

const defaultPatrolRoutes = [
  "You sweep the river marker path from the south beacon to Split Marker Three.",
  "You cover the wind-cut ditch between Black Pine gate and the chalk ridge.",
  "You trace the outer palisade markers where frost swallows old tracks.",
] as const;

const defaultCampRoutes = [
  "You remain in camp between the gate bench, ledger table, and signal post.",
  "You hold the barracks lane and ration hall while patrols rotate out.",
] as const;

function makeCard(spec: CardSpec): NightEventCard {
  return {
    id: spec.id,
    sceneType: spec.sceneType,
    title: spec.title,
    outcome: spec.outcome,
    tags: spec.tags,
    routeTemplates:
      spec.routeTemplates ??
      (spec.sceneType === "PATROL" ? [...defaultPatrolRoutes] : [...defaultCampRoutes]),
    basePlayerDelta: spec.player ?? {},
    baseCampDelta: spec.camp ?? {},
    observationPool: spec.observationPool,
  };
}

const mundaneSpecs: CardSpec[] = [
  {
    id: "mundane-patrol-quiet-fence",
    sceneType: "PATROL",
    title: "Quiet Fence Line",
    outcome: "The perimeter ropes hold and the snow reads as old foot traffic only.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { discipline: 1 },
    observationPool: [
      "Tracks on the fence line were old and weathered.",
      "No breach marks found on the stake row.",
      "Lantern posts burned steady all watch.",
    ],
  },
  {
    id: "mundane-patrol-cold-lantern",
    sceneType: "PATROL",
    title: "Cold Lantern Service",
    outcome: "You replace two weak lantern mantles before either post goes dark.",
    tags: ["mundane"],
    player: { stamina: -1, warmth: -1 },
    camp: { discipline: 1, morale: 1 },
    observationPool: [
      "North post lantern was replaced without incident.",
      "Oil levels now match the ledger count.",
      "No signs of tampering near maintenance crates.",
    ],
  },
  {
    id: "mundane-patrol-marker-reset",
    sceneType: "PATROL",
    title: "Marker Reset",
    outcome: "A drift-buried marker is raised and re-flagged for morning patrols.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { discipline: 1 },
    observationPool: [
      "Marker Four was recovered under packed drift.",
      "New cloth strip was tied at shoulder height.",
      "Route visibility improved for the next watch.",
    ],
  },
  {
    id: "mundane-patrol-river-ice",
    sceneType: "PATROL",
    title: "River Ice Survey",
    outcome: "Ice near the ford is stable enough for guarded crossing at dawn.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { supplies: 1 },
    observationPool: [
      "Ford ice remained intact under weighted probe.",
      "No fresh cracks near crossing poles.",
      "Route can support sled transport in daylight.",
    ],
  },
  {
    id: "mundane-patrol-clear-horizon",
    sceneType: "PATROL",
    title: "Clear Horizon",
    outcome: "The ridge remains empty and the weather holds for the full sweep.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { morale: 1 },
    observationPool: [
      "No movement reported along upper ridge.",
      "Signal mirrors returned clear line of sight.",
      "Wind remained predictable through final pass.",
    ],
  },
  {
    id: "mundane-patrol-sled-repair",
    sceneType: "PATROL",
    title: "Sled Brace Repair",
    outcome: "You secure a loose sled brace at the supply cut and prevent a breakdown.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { supplies: 1, discipline: 1 },
    observationPool: [
      "Cargo sled brace was tightened with field wire.",
      "Load remained balanced after repair.",
      "No damaged crates found at the cut.",
    ],
  },
  {
    id: "mundane-patrol-quiet-ravine",
    sceneType: "PATROL",
    title: "Quiet Ravine",
    outcome: "The ravine echoes carry clean and no false alarms are raised.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { rumor: -1 },
    observationPool: [
      "Ravine acoustics were normal through the watch.",
      "No calls repeated from the outer wall.",
      "Scout pair logged routine movement only.",
    ],
  },
  {
    id: "mundane-patrol-frost-gate",
    sceneType: "PATROL",
    title: "Frost Gate Check",
    outcome: "Gate pins are iced but functional and no one is missing from rotation.",
    tags: ["mundane"],
    player: { warmth: -1 },
    camp: { discipline: 1 },
    observationPool: [
      "Gate hinge ice was chipped clear.",
      "Pin lock seated correctly after reset.",
      "Headcount matched gate roster.",
    ],
  },
  {
    id: "mundane-patrol-messenger-pass",
    sceneType: "PATROL",
    title: "Messenger Pass",
    outcome: "A courier team clears the pass on schedule and delivers sealed orders.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { morale: 1 },
    observationPool: [
      "Courier route stayed open through dusk.",
      "Seal wax remained intact on delivery.",
      "Escort reported no detours.",
    ],
  },
  {
    id: "mundane-patrol-ember-watch",
    sceneType: "PATROL",
    title: "Ember Watch",
    outcome: "You keep a long quiet watch with no contacts and no losses.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { rumor: -1, morale: 1 },
    observationPool: [
      "Nothing unusual crossed your lane.",
      "Outer horn remained silent all watch.",
      "Lantern count matched outgoing shift log.",
    ],
  },
  {
    id: "mundane-camp-stable-count",
    sceneType: "CAMP",
    title: "Stable Count",
    outcome: "Ration, oil, and bolt counts all align before curfew bell.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { discipline: 1, rumor: -1 },
    observationPool: [
      "Inventory totals matched expected range.",
      "No tamper marks found on storage seals.",
      "Night clerks signed counts without dispute.",
    ],
  },
  {
    id: "mundane-camp-hearth-duty",
    sceneType: "CAMP",
    title: "Hearth Duty",
    outcome: "You rotate the hearth posts and the barracks settle into routine.",
    tags: ["mundane"],
    player: { warmth: 1 },
    camp: { morale: 1 },
    observationPool: [
      "Hearth posts remained staffed and calm.",
      "No barracks disputes after final meal.",
      "Night bell sounded on time.",
    ],
  },
  {
    id: "mundane-camp-ledger-pass",
    sceneType: "CAMP",
    title: "Ledger Pass",
    outcome: "Debrief records are copied cleanly with no contested entries.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { discipline: 1 },
    observationPool: [
      "Debrief sheets matched gate timestamps.",
      "No duplicate names in patrol return log.",
      "Commander approved closeout without edits.",
    ],
  },
  {
    id: "mundane-camp-wall-repair",
    sceneType: "CAMP",
    title: "Wall Stitch Repair",
    outcome: "A split windscreen is stitched before weather worsens.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { morale: 1, discipline: 1 },
    observationPool: [
      "South wall cloth was reinforced with spare cord.",
      "No water seeped into supply row overnight.",
      "Repair held through final gust checks.",
    ],
  },
  {
    id: "mundane-camp-quiet-mess",
    sceneType: "CAMP",
    title: "Quiet Mess Hall",
    outcome: "Meals run short but orderly, and the line turns in without argument.",
    tags: ["mundane"],
    player: { hunger: 1 },
    camp: { morale: 1, rumor: -1 },
    observationPool: [
      "Mess queue moved without incident.",
      "No verbal clashes near ration table.",
      "Final tray count matched duty roster.",
    ],
  },
  {
    id: "mundane-camp-harness-fix",
    sceneType: "CAMP",
    title: "Harness Fix",
    outcome: "Pack harnesses are mended ahead of tomorrow's hauling detail.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { supplies: 1 },
    observationPool: [
      "Three harness tears were repaired.",
      "No missing buckles in tool chest.",
      "Quartermaster cleared gear for duty.",
    ],
  },
  {
    id: "mundane-camp-sentry-drill",
    sceneType: "CAMP",
    title: "Sentry Drill",
    outcome: "A short drill sharpens call-and-response with no penalties.",
    tags: ["mundane"],
    player: { stamina: -1 },
    camp: { discipline: 1 },
    observationPool: [
      "Call signs were answered correctly.",
      "Drill ended before curfew window.",
      "No misses in relay timing.",
    ],
  },
  {
    id: "mundane-camp-letter-drop",
    sceneType: "CAMP",
    title: "Letter Drop",
    outcome: "A courier pouch arrives with mundane orders and keeps morale from slipping.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { morale: 1 },
    observationPool: [
      "Courier pouch contained routine dispatches.",
      "No emergency marks on parchment seals.",
      "Chain of custody remained intact.",
    ],
  },
  {
    id: "mundane-camp-frozen-pump",
    sceneType: "CAMP",
    title: "Frozen Pump",
    outcome: "The water pump freezes briefly, then returns after a controlled thaw.",
    tags: ["mundane"],
    player: { stamina: -1, warmth: -1 },
    camp: { discipline: 1 },
    observationPool: [
      "Pump arm freed after controlled heating.",
      "Water flow normalized before lights-out.",
      "No contamination found in storage barrels.",
    ],
  },
  {
    id: "mundane-camp-midnight-rollcall",
    sceneType: "CAMP",
    title: "Midnight Rollcall",
    outcome: "Rollcall closes fast and every bunk is accounted for.",
    tags: ["mundane"],
    player: { sanity: 1 },
    camp: { discipline: 1, rumor: -1 },
    observationPool: [
      "All bunks accounted for at final bell.",
      "No late absences from assigned barracks.",
      "Night clerk logged a clean close.",
    ],
  },
];

const ambiguousSignSpecs: CardSpec[] = [
  {
    id: "ambiguous-patrol-distant-flare",
    sceneType: "PATROL",
    title: "Distant Flare",
    outcome: "A brief light blooms beyond the ridge and vanishes before bearings settle.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2 },
    observationPool: [
      "A short flare was seen beyond marker range.",
      "No signal horn followed the light.",
      "Direction could not be confirmed.",
    ],
  },
  {
    id: "ambiguous-patrol-half-track",
    sceneType: "PATROL",
    title: "Half Track",
    outcome: "A single line of prints starts at hard ice and ends in clean snow.",
    tags: ["ambiguous"],
    player: { sanity: -1, stamina: -1 },
    camp: { rumor: 2 },
    observationPool: [
      "One trail ended without visible return.",
      "Snow crust nearby remained unbroken.",
      "Print depth suggested a weighted traveler.",
    ],
  },
  {
    id: "ambiguous-patrol-lost-howl",
    sceneType: "PATROL",
    title: "Lost Howl",
    outcome: "A long howl circles the post with no follow-up movement.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 1, morale: -1 },
    observationPool: [
      "Howl carried from multiple directions.",
      "No visual contact followed the sound.",
      "The echo faded near old stone markers.",
    ],
  },
  {
    id: "ambiguous-patrol-symbol-scrape",
    sceneType: "PATROL",
    title: "Symbol Scrape",
    outcome: "A shallow symbol appears on a drift board, then crumbles in wind.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2, discipline: -1 },
    observationPool: [
      "A rough mark appeared on packed snowboard.",
      "No tool tracks remained nearby.",
      "The mark collapsed before full sketching.",
    ],
  },
  {
    id: "ambiguous-patrol-lantern-echo",
    sceneType: "PATROL",
    title: "Lantern Echo",
    outcome: "A second lantern-glow mirrors your own for several breaths.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2 },
    observationPool: [
      "A mirrored glow tracked patrol movement briefly.",
      "No physical lamp source was found.",
      "Reflection ended near ditch bend.",
    ],
  },
  {
    id: "ambiguous-patrol-voice-behind",
    sceneType: "PATROL",
    title: "Voice Behind",
    outcome: "Someone calls from behind your file, but no one breaks formation.",
    tags: ["ambiguous"],
    player: { sanity: -2, stamina: -1 },
    camp: { rumor: 2 },
    observationPool: [
      "A familiar voice was heard off-column.",
      "No third party observed near patrol lane.",
      "Audio source could not be fixed.",
    ],
  },
  {
    id: "ambiguous-patrol-buried-bell",
    sceneType: "PATROL",
    title: "Buried Bell",
    outcome: "A bell tone rings under snowpack where no marker bell stands.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2, morale: -1 },
    observationPool: [
      "Bell tone repeated from below surface crust.",
      "No hardware found after probing.",
      "Sound ceased near second marker line.",
    ],
  },
  {
    id: "ambiguous-patrol-silent-campfire",
    sceneType: "PATROL",
    title: "Silent Campfire",
    outcome: "You find fresh ash with no footprints and no smoke trail.",
    tags: ["ambiguous"],
    player: { sanity: -1 },
    camp: { rumor: 2 },
    observationPool: [
      "Warm ash found near ridge hollow.",
      "No entry or exit prints nearby.",
      "No embers remained under top layer.",
    ],
  },
  {
    id: "ambiguous-patrol-moving-shadow",
    sceneType: "PATROL",
    title: "Moving Shadow",
    outcome: "A dark shape glides parallel to your route and disappears in sleet.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2 },
    observationPool: [
      "Dark movement tracked patrol line at distance.",
      "No prints found where shape vanished.",
      "Visibility dropped too quickly for pursuit.",
    ],
  },
  {
    id: "ambiguous-camp-quiet-dread",
    sceneType: "CAMP",
    title: "Quiet Dread",
    outcome: "No incident is logged, yet everyone speaks as if a warning already sounded.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { morale: -1, rumor: 2 },
    observationPool: [
      "No formal alert was called overnight.",
      "Barracks remained unusually quiet.",
      "Rumors repeated without source.",
    ],
  },
  {
    id: "ambiguous-camp-late-knock",
    sceneType: "CAMP",
    title: "Late Knock",
    outcome: "Three sharp knocks hit the south gate, but the watch window shows no one.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2, discipline: -1 },
    observationPool: [
      "Gate knock pattern was heard by two sentries.",
      "No contact visible at inspection slit.",
      "Outer snow remained undisturbed.",
    ],
  },
  {
    id: "ambiguous-camp-phantom-roster",
    sceneType: "CAMP",
    title: "Phantom Roster",
    outcome: "A duplicate name appears on the watch roster and fades when cross-checked.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2 },
    observationPool: [
      "Roster showed one duplicate entry briefly.",
      "Ink record did not retain the duplicate.",
      "No clerk admitted writing the line.",
    ],
  },
  {
    id: "ambiguous-camp-cold-whistle",
    sceneType: "CAMP",
    title: "Cold Whistle",
    outcome: "A patrol whistle sounds from empty stables after lights-out.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2, morale: -1 },
    observationPool: [
      "Whistle cadence matched patrol code.",
      "Stable lanes were empty on response.",
      "No gear moved from assigned racks.",
    ],
  },
  {
    id: "ambiguous-camp-sleepwalker",
    sceneType: "CAMP",
    title: "Sleepwalker",
    outcome: "A recruit walks the wall in silence and recalls none of it at dawn.",
    tags: ["ambiguous"],
    player: { sanity: -1 },
    camp: { morale: -1, rumor: 2 },
    observationPool: [
      "Recruit was found outside assigned bunk.",
      "No memory retained after wakeup.",
      "Patrol ladder was used without witness.",
    ],
  },
  {
    id: "ambiguous-camp-frost-script",
    sceneType: "CAMP",
    title: "Frost Script",
    outcome: "Symbols form on a shutter in frost and melt before anyone can trace them.",
    tags: ["ambiguous"],
    player: { sanity: -2 },
    camp: { rumor: 2 },
    observationPool: [
      "Frost markings appeared on inner shutter.",
      "Pattern vanished during documentation attempt.",
      "No matching chalk or blade marks found.",
    ],
  },
];

const hazardSpecs: CardSpec[] = [
  {
    id: "hazard-patrol-ice-sink",
    sceneType: "PATROL",
    title: "Ice Sink",
    outcome: "A scout drops through thin crust and must be hauled out under wind.",
    tags: ["hazard"],
    player: { stamina: -3, injury: 2 },
    camp: { morale: -1, rumor: 1 },
    observationPool: [
      "Surface crust failed under loaded step.",
      "Recovery rope held after second pull.",
      "No permanent loss reported.",
    ],
  },
  {
    id: "hazard-patrol-broken-sled",
    sceneType: "PATROL",
    title: "Broken Sled",
    outcome: "A cargo sled snaps at the ditch and spills supplies into packed snow.",
    tags: ["hazard"],
    player: { stamina: -3, injury: 1 },
    camp: { supplies: -2, rumor: 1 },
    observationPool: [
      "Sled axle fractured near ditch stones.",
      "Two crates were damaged in the spill.",
      "Drag marks moved toward treeline.",
    ],
  },
  {
    id: "hazard-patrol-fall-rock",
    sceneType: "PATROL",
    title: "Falling Rock",
    outcome: "Loose ridge stone drops across your route and forces a dangerous detour.",
    tags: ["hazard"],
    player: { stamina: -2, injury: 2 },
    camp: { discipline: -1, rumor: 1 },
    observationPool: [
      "Rockfall blocked marker path at ridge lip.",
      "No recent tool marks on unstable face.",
      "Detour time added to patrol return.",
    ],
  },
  {
    id: "hazard-patrol-whiteout",
    sceneType: "PATROL",
    title: "Flash Whiteout",
    outcome: "A sudden whiteout blinds the line and separates your rear pair.",
    tags: ["hazard", "ambiguous"],
    player: { stamina: -3, sanity: -1, injury: 1 },
    camp: { morale: -1, rumor: 2 },
    observationPool: [
      "Visibility dropped below one marker length.",
      "Rear pair rejoined after horn relay.",
      "No lasting separation after regroup.",
    ],
  },
  {
    id: "hazard-patrol-frozen-bridge",
    sceneType: "PATROL",
    title: "Frozen Bridge Slip",
    outcome: "A plank bridge ices over and one watcher takes a hard fall.",
    tags: ["hazard"],
    player: { stamina: -2, injury: 2 },
    camp: { morale: -1 },
    observationPool: [
      "Bridge deck iced through unexpectedly.",
      "One watcher fell but remained mobile.",
      "Crossing lane marked unsafe until thaw.",
    ],
  },
  {
    id: "hazard-patrol-snare-wire",
    sceneType: "PATROL",
    title: "Snare Wire",
    outcome: "A fine wire catches at shin height near a blind bend in the ditch.",
    tags: ["hazard", "internal"],
    player: { stamina: -2, injury: 2 },
    camp: { discipline: -1, rumor: 2 },
    observationPool: [
      "Wire snare was set along blind approach.",
      "No maker identified from knot style.",
      "Site was flagged for dawn inspection.",
    ],
  },
  {
    id: "hazard-camp-missing-crates",
    sceneType: "CAMP",
    title: "Missing Crates",
    outcome: "Two supply crates disappear between seal check and midnight count.",
    tags: ["hazard", "internal"],
    player: { sanity: -1 },
    camp: { supplies: -3, discipline: -1, rumor: 2 },
    observationPool: [
      "Two crate IDs failed at recount.",
      "Seal fragments found near rear door.",
      "No breach marks on outer wall.",
    ],
  },
  {
    id: "hazard-camp-bunk-fire",
    sceneType: "CAMP",
    title: "Bunk Fire",
    outcome: "A cot fire is smothered quickly, but gear and tempers are both scorched.",
    tags: ["hazard", "internal"],
    player: { stamina: -2, sanity: -1 },
    camp: { supplies: -1, morale: -2, rumor: 1 },
    observationPool: [
      "Fire source was contained within one bunk lane.",
      "No fatalities reported after response.",
      "Cause remained undetermined.",
    ],
  },
  {
    id: "hazard-camp-lost-medic-kit",
    sceneType: "CAMP",
    title: "Lost Medic Kit",
    outcome: "A medic kit goes missing before shift handoff and triage slows.",
    tags: ["hazard", "internal"],
    player: { sanity: -1 },
    camp: { supplies: -2, discipline: -1, rumor: 1 },
    observationPool: [
      "Medic kit pouch was not in assigned locker.",
      "Sign-out record had no matching entry.",
      "Backup stock covered urgent cases only.",
    ],
  },
  {
    id: "hazard-camp-collapsed-awning",
    sceneType: "CAMP",
    title: "Collapsed Awning",
    outcome: "Heavy sleet drops a work awning and injures a quartermaster runner.",
    tags: ["hazard"],
    player: { stamina: -1, injury: 1 },
    camp: { morale: -1, discipline: -1 },
    observationPool: [
      "Awning supports failed under wet load.",
      "One runner sustained minor injury.",
      "Repair crew patched the lane overnight.",
    ],
  },
];

const internalConflictSpecs: CardSpec[] = [
  {
    id: "internal-patrol-command-split",
    sceneType: "PATROL",
    title: "Command Split",
    outcome: "Two sergeants issue conflicting route calls and the patrol stalls.",
    tags: ["internal"],
    player: { sanity: -1, stamina: -1 },
    camp: { discipline: -2, morale: -1, rumor: 1 },
    observationPool: [
      "Route command dispute delayed movement.",
      "No consensus reached before fallback call.",
      "Debrief requested command clarification.",
    ],
  },
  {
    id: "internal-patrol-credit-dispute",
    sceneType: "PATROL",
    title: "Credit Dispute",
    outcome: "A scouting claim turns into a public argument before return bell.",
    tags: ["internal"],
    player: { sanity: -1 },
    camp: { discipline: -1, morale: -1, rumor: 2 },
    observationPool: [
      "Two scouts disputed claim ownership.",
      "Argument continued after handoff.",
      "No formal reprimand issued yet.",
    ],
  },
  {
    id: "internal-patrol-ration-hoard",
    sceneType: "PATROL",
    title: "Ration Hoard",
    outcome: "Hidden ration tins are found in a patrol satchel during check.",
    tags: ["internal", "hazard"],
    player: { sanity: -1 },
    camp: { supplies: -1, discipline: -2, rumor: 2 },
    observationPool: [
      "Unauthorized ration tins recovered from patrol pack.",
      "Serial marks matched camp inventory.",
      "Owner denied intent to steal.",
    ],
  },
  {
    id: "internal-patrol-unauthorized-detour",
    sceneType: "PATROL",
    title: "Unauthorized Detour",
    outcome: "A flank pair leaves the marked lane and returns with thin excuses.",
    tags: ["internal"],
    player: { stamina: -1, sanity: -1 },
    camp: { discipline: -2, rumor: 1 },
    observationPool: [
      "Two watchers left marked route without order.",
      "Debrief explanation remained inconsistent.",
      "No contact logged on detour path.",
    ],
  },
  {
    id: "internal-camp-hearth-argument",
    sceneType: "CAMP",
    title: "Hearth Argument",
    outcome: "Debrief order turns into shouted accusations in the hall.",
    tags: ["internal"],
    player: { sanity: -1 },
    camp: { morale: -2, discipline: -2, rumor: 2 },
    observationPool: [
      "Debrief queue broke into argument.",
      "No physical fight after intervention.",
      "Multiple squads left without closure.",
    ],
  },
  {
    id: "internal-camp-missing-signature",
    sceneType: "CAMP",
    title: "Missing Signature",
    outcome: "A watch order cannot be validated because command signatures don't match.",
    tags: ["internal"],
    player: { sanity: -1 },
    camp: { discipline: -2, rumor: 1 },
    observationPool: [
      "Order sheet carried inconsistent signatures.",
      "Clerk could not verify issuing officer.",
      "Temporary command gap opened overnight.",
    ],
  },
  {
    id: "internal-camp-barracks-fracture",
    sceneType: "CAMP",
    title: "Barracks Fracture",
    outcome: "Squads split over curfew enforcement and refuse a shared detail.",
    tags: ["internal"],
    player: { sanity: -1 },
    camp: { morale: -2, discipline: -1, rumor: 2 },
    observationPool: [
      "Two barracks groups rejected a mixed detail.",
      "Curfew enforcement became uneven.",
      "Captain logged the split as unresolved.",
    ],
  },
  {
    id: "internal-camp-kitchen-blame",
    sceneType: "CAMP",
    title: "Kitchen Blame",
    outcome: "Spoiled rations spark blame between cooks and quartermasters.",
    tags: ["internal", "hazard"],
    player: { sanity: -1 },
    camp: { supplies: -1, morale: -1, rumor: 2 },
    observationPool: [
      "Spoilage discovered during late meal prep.",
      "Storage handling dispute escalated quickly.",
      "No contamination source confirmed.",
    ],
  },
  {
    id: "internal-camp-gate-favoritism",
    sceneType: "CAMP",
    title: "Gate Favoritism",
    outcome: "Gate assignments are accused of favoritism and trust erodes.",
    tags: ["internal"],
    player: { sanity: -1 },
    camp: { morale: -1, discipline: -1, rumor: 2 },
    observationPool: [
      "Assignment board edits triggered complaints.",
      "Gate captain denied preferential treatment.",
      "Multiple requests for review were filed.",
    ],
  },
  {
    id: "internal-camp-accusation-chain",
    sceneType: "CAMP",
    title: "Accusation Chain",
    outcome: "One theft accusation becomes three before midnight and none are proven.",
    tags: ["internal"],
    player: { sanity: -2 },
    camp: { discipline: -1, rumor: 3 },
    observationPool: [
      "Theft allegation spread through three squads.",
      "No direct evidence submitted by dawn.",
      "Command ordered temporary silence on claims.",
    ],
  },
];

const shockSpecs: CardSpec[] = [
  {
    id: "shock-patrol-vanished-pair",
    sceneType: "PATROL",
    title: "Vanished Pair",
    outcome: "Two watchers disappear between marker checks, leaving dropped lamps in clean snow.",
    tags: ["shock", "hazard", "ambiguous"],
    player: { stamina: -4, sanity: -4, injury: 2 },
    camp: { morale: -3, discipline: -1, rumor: 4 },
    observationPool: [
      "Two patrol lamps found without carriers.",
      "No drag signs near marker lane.",
      "Search line failed to recover the pair.",
    ],
  },
  {
    id: "shock-patrol-red-moon-alarm",
    sceneType: "PATROL",
    title: "Red Moon Alarm",
    outcome: "A blood-red moonrise triggers panic calls and a full false alarm run.",
    tags: ["shock", "ambiguous"],
    player: { sanity: -4, stamina: -2 },
    camp: { morale: -2, discipline: -1, rumor: 4 },
    observationPool: [
      "Alarm relay was triggered by sky condition.",
      "No hostile contact found during sweep.",
      "Panic spread before cancellation order.",
    ],
  },
  {
    id: "shock-patrol-gate-breach-scare",
    sceneType: "PATROL",
    title: "Gate Breach Scare",
    outcome: "A hinge failure sounds like forced entry and the line scrambles blind.",
    tags: ["shock", "hazard", "internal"],
    player: { stamina: -3, sanity: -3, injury: 1 },
    camp: { discipline: -2, morale: -2, rumor: 3 },
    observationPool: [
      "Gate hinge snapped under frost pressure.",
      "Emergency breach call was sent in error.",
      "Response lines crossed and delayed recall.",
    ],
  },
  {
    id: "shock-camp-mutiny-whisper",
    sceneType: "CAMP",
    title: "Mutiny Whisper",
    outcome: "A rumor of mutiny reaches command tent and fractures trust overnight.",
    tags: ["shock", "internal"],
    player: { sanity: -3 },
    camp: { morale: -3, discipline: -2, rumor: 4 },
    observationPool: [
      "Mutiny claim surfaced in command corridor.",
      "No signed statement supported the claim.",
      "Counter-orders were issued before dawn.",
    ],
  },
  {
    id: "shock-camp-body-at-gate",
    sceneType: "CAMP",
    title: "Body at the Gate",
    outcome: "A frozen body appears at dawn gate with no tracks leading in.",
    tags: ["shock", "hazard", "ambiguous"],
    player: { sanity: -4, injury: 1 },
    camp: { morale: -3, rumor: 5, discipline: -1 },
    observationPool: [
      "Body was discovered at first gate inspection.",
      "Approach path showed no fresh tracks.",
      "Identity remained unconfirmed at report close.",
    ],
  },
];

const ambiguousSignCards = ambiguousSignSpecs.map((spec) => makeCard(spec));
const hazardCards = hazardSpecs.map((spec) => makeCard(spec));
const internalConflictCards = internalConflictSpecs.map((spec) => makeCard(spec));
const mundaneCards = mundaneSpecs.map((spec) => makeCard(spec));
const shockCards = shockSpecs.map((spec) => makeCard(spec));

export const eventCardCatalog = {
  mundane: mundaneCards,
  ambiguous: ambiguousSignCards,
  hazard: hazardCards,
  internal: internalConflictCards,
  shock: shockCards,
} as const;

export const nightEventCards: NightEventCard[] = [
  ...eventCardCatalog.mundane,
  ...eventCardCatalog.ambiguous,
  ...eventCardCatalog.hazard,
  ...eventCardCatalog.internal,
  ...eventCardCatalog.shock,
];
